config/routes.rb
Website::Application.routes.draw do
  get "main_page/index"
  match '/about', to: "main_page#about"
  match '/contact', to: "main_page#contact"
  match '/support', to: "main_page#support"

   root :to => 'MainPage#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	def check_for_mobile
		session[ :mobile_override ] = params[ :mobile ] if params[ :mobile ]
		prepare_for_mobile if mobile_device?
	end
	
	def prepare_for_mobile
		prepend_view_path Rails.root + 'app' + 'views_mobile'
	end

	def mobile_device?
		if session[ :mobile_override ]
			session[ :mobile_override ] == "1"
		else
			(request.user_agent =~ /Mobile|webOS/) && (request.user_agent !~ /iPad/)
		end
	end
	helper_method :mobile_device?
end

app/controllers/main_mobile_controller.rb
class MainMobileController < ApplicationController
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
	before_filter :check_for_mobile, :only => [ :new, :edit, :index ]
	before_filter :prepare_for_mobile, :only => :show
  def index
	print 'Laurel Tree Computing LLC'
  end

  def contact
  end

  def about
  end

  def support
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_mobile_helper.rb
module MainMobileHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/layouts/_footer.html.erb
<div class="row-fluid">
	<div class="center span1">
		<%= link_to image_tag("http://www.w3.org/html/logo/badge/html5-badge-h-css3-semantics.png",
			:alt => "HTML5 Powered with CSS3 / Styling, and Semantics",
			:title => "HTML5 Powered with CSS3 / Styling, and Semantics"),
				"http://www.w3.org/html/logo/" %>
	</div>
	<div class="center span1">
		<%= link_to image_tag("rails.png", alt:"Rails"), 'http://rubyonrails.org/' %>
	</div>
</div>
<footer class="footer row">
	<small>
		Website design by Laurel Tree Computing LLC. © 2012 All Rights Reserved.
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<nav class="resizable">
				<ul id='navbar' class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li class="dropdown"><a href='#' class="dropdown-toggle"
							data-toggle="dropdown">Services<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href='#'>Software Development</a></li>
								<li><a href='#'>Hardware/Software Support</a></li>
							<li><a href='#'>Systems/Networking</a></li>
						</ul>
					</li>
					<li><%= link_to "Support", support_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Laurel Tree Computing LLC</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer'%>
	</div>
</body>
</html>

app/views/main_page/contact.html.erb
<%= provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Laurel Tree Computing <%= link_to 'main_page/contact', "here"%>.
</p>

app/views/main_page/index.html.erb
<!-- <div id='container'><div id='progressbar'></div></div> -->
<div id='middle' class="hero-unit center row">
	<div id='header' class="span12">
		<div class="center row-fluid">
			<div class="span2">
				<%= image_tag 'Color Laurel Tree.svg', :id => 'logo', :class => 'img-circle'%>
			</div>
			<div id='head1div' class="span6 offset1">
				<h1 id='head1' class='page-header resizable acontent'>Laurel Tree Computing LLC</h1>
			</div>
		</div>
	</div>
</div>
<div class="row-fluid">
	<div id='underbody' class="row hero-unit well well-small">
		<div id='underbodydiv' class="span10 offset1">
			<div class='center'>
				<h2>News</h2>
				<p class='lead acontent'>Welcome to our website!</p>
			</div>
			<div>
				<p class='alert alert-info'><button type="button" class="close" data-dismiss="alert">×</button><strong>Info:</strong>This site is currently under maintenance and we apologize if something is broken.</p>
				<p class='alert alert-info'><button type="button" class="close" data-dismiss="alert">×</button><strong>Info:</strong>If you find something wrong, send us an email and let us know what doesn't work for you.</p>
			</div>
			<div>
				<h3>Our content isn't exactly static....</h3>
				<p class='info acontent'>Please feel free to <strong>drag</strong> any content on this page around and <strong>rearrange</strong> it.</p>
				<h4>Play Around.....Have Fun</h4>
				<p class='info acontent'>Each item can also be <em class="text-info">resized</em> by <strong>pulling</strong> on corner triangle attached to each piece of content.</p>
			</div>
			<div id='contact'>
				<p id='email'><small>Email us for information regarding our services and software at <%= mail_to "info@laureltreecomputing.com",nil, :replace_at => '_at_', :replace_dot => '_dot_' %></small></p>
			</div>
		</div>
	</div>
</div>